### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by FlorianOtel**
* Fixed error message structure in error.go 

* Added HTTP transaction logging (optional debugging) in session.go

* Removed _test.go that break go linters.

### CODE REVIEW

**Comment by pdellaert** [comment]
Why did you delete the tests instead of adapting them?

**Comment by FlorianOtel** [comment]
Because:

1) I don't have yet a test framework in place that works satisfactory to
adapt them to.

2) We haven't (yet) agreed on one (good point though)

3) Why do we need one when there's barely someone maintaining this
particular repo (rather small to begin with) ?

**Comment by primalmotion** [comment]
Wow. Removing the tests because they break your linter and because you don't have the dependencies installed locally, that's something...

**Comment by FlorianOtel** [comment]
Antoine,

I understand this may sound puzzling, but there's a deeper reason behind
this "logic".

Let me start in reverse order

- Pulling all dependencies locally is regularly- and unfortunately with
increasing frequency- a problem. This to the point that doing a "go get
..." on my systems nowadays spews huge amounts of errrors and inevitably
breaks the system. For a recent example see the huge problems Kubernetes
has with refactoring their package dependencies

That is why I have a "very strong preference" for package vendoring. Still,
 that is far less than optimal, since having everything vendored is not an
option either, so we're working hard to strike a balance between the two.

- wrt breaking the linter. The reason I'm "rather strict" (read: anal)
about this is because - as you may know too well... - the code that we need
to deal with internally is all over the place (literally). Not saying that
this is the case here - on the contrary- but, ironically,  it's easier to
start with such pedantic cases than suddenly enforce "strict idiomatic
discipline" on major components.

Also, and most importantly, we are now evaluating alternative unit testing
frameworks that have a much larger applicability than just this. Still,
we're not there yet, but the first step to get there is to return to a
clean slate (remove tests)

Hope this explains in detail the rationale.

**Pull request closed without merging**
